### ISSUE TITLE
code cannot generate training data when running train.py

### ISSUE THREAD

**Issue by TaylorWisdom1** [kaustabpal/ATPPNet#1]
I tried your code and noticed that the code cannot automatically generate training data when running train.py. 
according to your code illustration, I set "PCF_DATA_RAW" and "PCF_DATA_PROCESSED" as the environment variables. However, when I run train.py the data I stored at "/path/to/kitti-odometry/dataset/sequences" has not been called to generate training data and saved in the path:/desired/path/to/processed/data/.  I am not sure whether I should make some other settings so that I can correctly run the code? by the way, I set GENERATE_FILES=True. but unfortunately, this parameter has not been called. So could you please give me some advice? 
Thank you in advance!

**Comment by ADI201998** [comment]
Hi @TaylorWisdom1 ,
There's a function `prepare_data` in the file `datasets.py` which is not being called in `train.py`, which might be the reason the training data is not being generated. 
Could you add the line `data.prepare_data()` before `data.setup()` with `GENERATE_FILES=True` and see if the training data is being generated?

**Comment by TaylorWisdom1** [comment]
Thank you for your advice.
I run “prepare_data” function and it seems the data can be correctly generated.
Thank you very much!
